log:
  level: warn
  # we are using sentry for error collection,
  # you could opt-out by disabling it on the following line
  disable_sentry: false

sentry:
  dsn: https://591b6a3c375f4aa890a37532ce4969ec@sentry.tokend.services/4

horizon:
  endpoint: http://horizon
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

coinpayments:
  merchant_id: "6936542314febfcc8dd3955fce88e0be"
  address: https://www.coinpayments.net/api.php
  private_key: "1004f66dB4081cA6D9c3f0651A1DC64eB754158e48daFb7441c4B632D26628eC"
  public_key: "f1db0de9c54cac677109f9da823b9627bef1c606fa75634c776100b88170a271"
  ipn_secret: "supersekr1tandsecure"
  request_timeout: 30

deposit_verify:
  source: GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4